name: nightly


on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *
jobs:
  dist-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download Odin
      shell: cmd
      run: git clone https://github.com/odin-lang/Odin
    - name: Download and unpack LLVM bins
      shell: powershell
      run: |
          cd Odin
          cd bin
          $ProgressPreference = "SilentlyContinue";
          Invoke-WebRequest -Uri https://github.com/odin-lang/Odin/releases/download/llvm-windows/llvm-binaries.zip -OutFile llvm-binaries.zip
          7z x llvm-binaries.zip > $null 
    - name: Build Odin
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
        cd Odin
        ./build.bat 1
    - name: Build ols
      shell: cmd
      run: ./build.bat CI
    - name: Move to Dist
      shell: cmd
      run: | 
        mkdir dist
        copy ols.exe dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-x86_64-pc-windows-msvc
        path: ./dist
  publish:
    name: publish
    runs-on: ubuntu-16.04
    needs: ['dist-x86_64-pc-windows-msvc']
    steps:
    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ env.FETCH_DEPTH }}

    - run: echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
    - run: 'echo "HEAD_SHA: $HEAD_SHA"'
    
    - uses: actions/download-artifact@v1
      with:
        name: dist-x86_64-pc-windows-msvc
        path: dist
    - run: ls -al ./dist
    
    - name: Publish Release
      uses: ./.github/actions/github-release
      with:
        files: "dist/*"
        name: "nigthly"
        token: ${{ secrets.GITHUB_TOKEN }}
